import { ExtractionResponse } from "./ai/schema";

// A hand-written stand-in for what /api/extract would return for a real menu image —
// same shape as a live extraction response. Lets reviewers exercise the upload -> extract ->
// review pipeline with no API key. Swapping this for a real captured extraction (e.g. from
// Menu_1.pdf/Menu_2.pdf once live-tested) later is a pure data swap, no code changes needed.
export const SAMPLE_EXTRACTION: ExtractionResponse = {
  legend: "V = Vegetarian",
  items: [
    {
      name: "Margherita Pizza",
      section: "Pizzas",
      description: "Tomato, mozzarella, fresh basil.",
      price: { amount: 8, currency: "EUR" },
      variant_label: "Small",
      variant_group: "Margherita Pizza",
      dietary_tags: [{ label: "Vegetarian", evidence: "'V' marker next to item; legend: V = Vegetarian" }],
      has_photo: true,
      confidence: 0.93,
      source_page_index: null,
    },
    {
      name: "Margherita Pizza",
      section: "Pizzas",
      description: "Tomato, mozzarella, fresh basil.",
      price: { amount: 14, currency: "EUR" },
      variant_label: "Large",
      variant_group: "Margherita Pizza",
      dietary_tags: [{ label: "Vegetarian", evidence: "'V' marker next to item; legend: V = Vegetarian" }],
      has_photo: false,
      confidence: 0.93,
      source_page_index: null,
    },
    {
      name: "Pepperoni Pizza",
      section: "Pizzas",
      description: "Tomato, mozzarella, spicy pepperoni.",
      price: { amount: 9.5, currency: "EUR" },
      variant_label: "Small",
      variant_group: "Pepperoni Pizza",
      dietary_tags: [],
      has_photo: false,
      confidence: 0.91,
      source_page_index: null,
    },
    {
      name: "Pepperoni Pizza",
      section: "Pizzas",
      description: "Tomato, mozzarella, spicy pepperoni.",
      price: { amount: 16, currency: "EUR" },
      variant_label: "Large",
      variant_group: "Pepperoni Pizza",
      dietary_tags: [],
      has_photo: false,
      confidence: 0.91,
      source_page_index: null,
    },
    {
      name: "Garlic Bread",
      section: "Starters",
      description: "Toasted bread with garlic butter and herbs.",
      price: { amount: 4.5, currency: "EUR" },
      variant_label: null,
      variant_group: null,
      dietary_tags: [{ label: "Vegetarian", evidence: "'V' marker next to item; legend: V = Vegetarian" }],
      has_photo: true,
      confidence: 0.95,
      source_page_index: null,
    },
    {
      name: "Tiramisu",
      section: "Desserts",
      description: "Classic Italian dessert with coffee-soaked sponge and mascarpone.",
      price: null,
      variant_label: null,
      variant_group: null,
      dietary_tags: [],
      has_photo: false,
      confidence: 0.55,
      source_page_index: null,
    },
  ],
};
