import { Restaurant } from "./types";

// Two hand-built mock restaurants that always appear on the restaurant list, so reviewers can
// exercise the full review UI — section grouping, red-bordered mandatory fields, variants,
// stated vs. inferred dietary tags — with no API key and no upload required.

const TAPAS: Restaurant = {
  id: "restaurant_mock_tapas",
  name: "Tapas & Co.",
  menus: [{ id: "menu_mock_tapas_lunch", name: "Main menu", fileName: "lunch-menu.pdf" }],
  items: [
    {
      id: "item_mock_tapas_1",
      menuId: "menu_mock_tapas_lunch",
      sourcePageLabel: "Page 1",
      sourceFileName: "lunch-menu.pdf",
      name: "Patatas Bravas",
      section: "Tapas",
      description: "Crispy fried potatoes with a spicy bravas sauce and aioli.",
      price: { amount: 5.5, currency: "EUR" },
      variant_label: "Ración",
      variant_group: "Patatas Bravas",
      dietary_tags: [{ label: "Vegetarian", source: "stated", evidence: "'V' marker next to item; legend: V = Vegetarian" }],
      has_photo: true,
      photoUrl: null,
      confidence: 0.92,
      description_is_ai_draft: false,
      approved: false,
    },
    {
      id: "item_mock_tapas_2",
      menuId: "menu_mock_tapas_lunch",
      sourcePageLabel: "Page 1",
      sourceFileName: "lunch-menu.pdf",
      name: "Patatas Bravas",
      section: "Tapas",
      description: "Crispy fried potatoes with a spicy bravas sauce and aioli.",
      price: { amount: 3.5, currency: "EUR" },
      variant_label: "Media ración",
      variant_group: "Patatas Bravas",
      dietary_tags: [{ label: "Vegetarian", source: "stated", evidence: "'V' marker next to item; legend: V = Vegetarian" }],
      has_photo: false,
      photoUrl: null,
      confidence: 0.88,
      description_is_ai_draft: false,
      approved: false,
    },
    {
      id: "item_mock_tapas_3",
      menuId: "menu_mock_tapas_lunch",
      sourcePageLabel: "Page 1",
      sourceFileName: "lunch-menu.pdf",
      name: "Jamón Ibérico",
      section: "Tapas",
      description: null,
      price: { amount: 12, currency: "EUR" },
      variant_label: null,
      variant_group: null,
      dietary_tags: [],
      has_photo: false,
      photoUrl: null,
      confidence: 0.95,
      description_is_ai_draft: false,
      approved: false,
    },
    {
      id: "item_mock_tapas_4",
      menuId: "menu_mock_tapas_lunch",
      sourcePageLabel: "Page 1",
      sourceFileName: "lunch-menu.pdf",
      name: "Tortilla Española",
      section: "Tapas",
      description: "Classic Spanish omelette with potato and onion.",
      price: null,
      variant_label: null,
      variant_group: null,
      dietary_tags: [{ label: "Vegetarian", source: "inferred", evidence: "Dish is traditionally egg, potato and onion only — no meat or fish typically used." }],
      has_photo: false,
      photoUrl: null,
      confidence: 0.6,
      description_is_ai_draft: false,
      approved: false,
    },
  ],
};

const SUB_STATION: Restaurant = {
  id: "restaurant_mock_subs",
  name: "Sub Station",
  menus: [{ id: "menu_mock_subs_main", name: "Main menu", fileName: "main-menu.jpg" }],
  items: [
    {
      id: "item_mock_subs_1",
      menuId: "menu_mock_subs_main",
      sourcePageLabel: "Page 1",
      sourceFileName: "main-menu.jpg",
      name: "Veggie Sub",
      section: "Sandwiches",
      description: "Fresh vegetables, cheese, and your choice of sauce on a footlong roll.",
      price: { amount: 8.5, currency: "EUR" },
      variant_label: "Footlong",
      variant_group: "Veggie Sub",
      dietary_tags: [{ label: "Vegetarian", source: "stated", evidence: "Item explicitly labelled '(vegetarian)' on the menu." }],
      has_photo: true,
      photoUrl: null,
      confidence: 0.9,
      description_is_ai_draft: false,
      approved: false,
    },
    {
      id: "item_mock_subs_2",
      menuId: "menu_mock_subs_main",
      sourcePageLabel: "Page 1",
      sourceFileName: "main-menu.jpg",
      name: "Veggie Sub",
      section: "Sandwiches",
      description: "Fresh vegetables, cheese, and your choice of sauce on a 6-inch roll.",
      price: { amount: 5, currency: "EUR" },
      variant_label: "6 inch",
      variant_group: "Veggie Sub",
      dietary_tags: [{ label: "Vegetarian", source: "stated", evidence: "Item explicitly labelled '(vegetarian)' on the menu." }],
      has_photo: false,
      photoUrl: null,
      confidence: 0.9,
      description_is_ai_draft: false,
      approved: false,
    },
    {
      id: "item_mock_subs_3",
      menuId: "menu_mock_subs_main",
      sourcePageLabel: "Page 1",
      sourceFileName: "main-menu.jpg",
      name: "Cola",
      section: null,
      description: null,
      price: { amount: 2.5, currency: "EUR" },
      variant_label: null,
      variant_group: null,
      dietary_tags: [],
      has_photo: false,
      photoUrl: null,
      confidence: 0.7,
      description_is_ai_draft: false,
      approved: false,
    },
  ],
};

export const SAMPLE_RESTAURANTS: Restaurant[] = [TAPAS, SUB_STATION];
